apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-dynamic
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: <file system ID>
  directoryPerms: "700"
  basePath: "/expense"
