apiVersion: v1
kind: Pod
metadata:
  name: env

spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: DevOps
    - name: student
      value: "kumar"
    - name: duration
      value: "120 HRS"
