apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  #labels for Deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
  #matching with defined labels for creation of resources
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        #image: joindevops/deployment:2.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ser
spec:
  type: LoadBalancer
  selector: #labels are used as selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80
    nodePort: 30007




